/* #!oprimp_auto_generated!# !! Do NOT remove this line */
/* eslint-disable */
// noinspection SpellCheckingInspection

/* Generated by OPRA Code Generator, Version 1.21.0 */
/*
 * undefined
 * Id: e3023b67a2e3307059640dfdb5f80f1a
 * Version: undefined
 * http://localhost:3001
 */

import { kClient, OpraHttpClient } from '@opra/client';
import { ShipmentController } from './api/ShipmentController';

/** 
 * Cargo API
 * @class OpraCargo
 * @url http:/localhost:3001/$schema
 */
export class OpraCargo {
  readonly [kClient]: OpraHttpClient;
  readonly $shipment: ShipmentController;

  constructor(client: OpraHttpClient) {
    this[kClient] = client;
    this.$shipment = new ShipmentController(client);
  }
}