/* #!oprimp_auto_generated!# !! Do NOT remove this line */
/* eslint-disable */
// noinspection SpellCheckingInspection

/* Generated by OPRA Code Generator, Version 1.21.0 */
/*
 * undefined
 * Id: e3023b67a2e3307059640dfdb5f80f1a
 * Version: undefined
 * http://localhost:3001
 */

import { ShipmentStatus } from '../enums/ShipmentStatus';
import { datetime } from '../../references/OpraBuiltInTypes/simple-types';

/**
 * Shipment (Cargo) details
 *
 * @url http:/localhost:3001/$schema/#types/ShipmentType
 */
export interface ShipmentType {
  /**
   * 
   */
  id?: string;

  /**
   * 
   */
  productId?: string;

  /**
   * 
   */
  userId?: string;

  /**
   * 
   */
  status?: ShipmentStatus;

  /**
   * 
   */
  createdAt?: datetime;
}

