/* #!oprimp_auto_generated!# !! Do NOT remove this line */
/* eslint-disable */
// noinspection SpellCheckingInspection

/* Generated by OPRA Code Generator, Version 1.21.0 */
/*
 * undefined
 * Id: e3023b67a2e3307059640dfdb5f80f1a
 * Version: undefined
 * http://localhost:3001
 */

/**
 * Shipping status
 *
 * @url http:/localhost:3001/$schema/#types/ShipmentStatus
 */
export enum ShipmentStatus {
  PENDING = 'PENDING',

  IN_TRANSIT = 'IN_TRANSIT',

  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',

  DELIVERED = 'DELIVERED',

  AT_FACILITY = 'AT_FACILITY',

  FAILED_DELIVERY = 'FAILED_DELIVERY',

}

