/* #!oprimp_auto_generated!# !! Do NOT remove this line */
/* eslint-disable */
// noinspection SpellCheckingInspection

/* Generated by OPRA Code Generator, Version 1.21.0 */
/*
 * undefined
 * Id: 26385b66f3cc91470d992c4b20ab256e
 * Version: undefined
 * http://localhost:3000
 */

import { OperationResult } from '@opra/common';
import { HttpRequestObservable, kClient, OpraHttpClient } from '@opra/client';
import { PartialDTO, DTO } from 'ts-gems';
import { HttpControllerNode } from '../http-controller-node';
import { ProductType } from '../models/types/ProductType';

/** 
 * Products collection
 * @class ProductController
 * @apiUrl http:/localhost:3000/products
 */
export class ProductController extends HttpControllerNode {

  /**
   * @param {OpraHttpClient} client - OpraHttpClient instance to operate
   * @constructor
   */  
  constructor(client: OpraHttpClient) {
    super(client);
  }

  /** 
   * findMany operation
   * @param {object} $params - Available parameters for the operation
   * @param {object} [$params.limit]  - Determines number of returning instances
   * @param {object} [$params.skip]  - Determines number of returning instances
   * @param {boolean} [$params.count]  - Counts all matching instances if enabled
   * @param {object[]} [$params.projection]  - Determines fields projection
   * @apiUrl http:/localhost:3000/products    
   */
  findMany(
    $params?: {
      limit?: number;
      skip?: number;
      count?: boolean;
      projection?: string[];
      filter?: string | any;
    }
  ): HttpRequestObservable<OperationResult<PartialDTO<ProductType>[]>>{
    const url = this._prepareUrl('/products', {});
    return this[kClient].request(url, { method: 'GET', params: $params as any});
  };

  /** 
   * get operation
   * @param {object} $params - Available parameters for the operation
   * @param {object[]} [$params.projection]  - Determines fields projection
   * @apiUrl http:/localhost:3000/products    
   */
  get(
    $params?: {
      projection?: string[];
    }
  ): HttpRequestObservable<OperationResult<PartialDTO<ProductType>> | undefined>{
    const url = this._prepareUrl('/products', {});
    return this[kClient].request(url, { method: 'GET', params: $params as any});
  };

  /** 
   * create operation
   * @param {ProductType} $body  - Product schema
   * @param {object} $params - Available parameters for the operation
   * @param {object[]} [$params.projection]  - Determines fields projection
   * @apiUrl http:/localhost:3000/products    
   */
  create($body: DTO<ProductType>, 
    $params?: {
      projection?: string[];
    }
  ): HttpRequestObservable<OperationResult<PartialDTO<ProductType>>>{
    const url = this._prepareUrl('/products', {});
    return this[kClient].request(url, { method: 'POST', body: $body, params: $params as any});
  };

  /** 
   * update operation
   * @param {ProductType} $body  - Product schema
   * @param {object} $params - Available parameters for the operation
   * @param {object[]} [$params.projection]  - Determines fields projection
   * @apiUrl http:/localhost:3000/products    
   */
  update($body: PartialDTO<ProductType>, 
    $params?: {
      projection?: string[];
    }
  ): HttpRequestObservable<OperationResult<PartialDTO<ProductType>> | undefined>{
    const url = this._prepareUrl('/products', {});
    return this[kClient].request(url, { method: 'PATCH', body: $body, params: $params as any});
  };

  /** 
   * delete operation
   * @apiUrl http:/localhost:3000/products    
   */
  delete(
  ): HttpRequestObservable<OperationResult>{
    const url = this._prepareUrl('/products', {});
    return this[kClient].request(url, { method: 'DELETE'});
  };
}