/* #!oprimp_auto_generated!# !! Do NOT remove this line */
/* eslint-disable */
// noinspection SpellCheckingInspection

/* Generated by OPRA Code Generator, Version 1.21.0 */
/*
 * undefined
 * Id: e3023b67a2e3307059640dfdb5f80f1a
 * Version: undefined
 * http://localhost:3001
 */

export * from './enums/ShipmentStatus';
export * from './types/ShipmentType';

