/* #!oprimp_auto_generated!# !! Do NOT remove this line */
/* eslint-disable */
// noinspection SpellCheckingInspection

/* Generated by OPRA Code Generator, Version 1.21.0 */
/*
 * undefined
 * Id: 058f9f43c1e667cf3ad9c1a0dff3cc62
 * Version: undefined
 * http://localhost:3000
 */

/**
 * Login payload
 *
 * @url http:/localhost:3000/$schema/#types/LoginInputType
 */
export interface LoginInputType {
  /**
   * 
   */
  email: string;

  /**
   * 
   */
  password: string;
}

