/* #!oprimp_auto_generated!# !! Do NOT remove this line */
/* eslint-disable */
// noinspection SpellCheckingInspection

/* Generated by OPRA Code Generator, Version 1.21.0 */
/*
 * undefined
 * Id: 058f9f43c1e667cf3ad9c1a0dff3cc62
 * Version: undefined
 * http://localhost:3000
 */

import { integer } from '../../references/OpraBuiltInTypes/simple-types';

/**
 * Product schema
 *
 * @url http:/localhost:3000/$schema/#types/ProductType
 */
export interface ProductType {
  /**
   * Product ID
   */
  id?: string;

  /**
   * 
   */
  name: string;

  /**
   * 
   */
  sku: string;

  /**
   * 
   */
  description?: string;

  /**
   * 
   */
  image?: string;

  /**
   * 
   */
  price: number;

  /**
   * 
   */
  stock?: integer;

  /**
   * 
   */
  isActive?: boolean;
}

