/* #!oprimp_auto_generated!# !! Do NOT remove this line */
/* eslint-disable */
// noinspection SpellCheckingInspection

/* Generated by OPRA Code Generator, Version 1.21.0 */
/*
 * undefined
 * Id: 416c049ef2d4b419053eb62787a4293c
 * Version: undefined
 * http://localhost:3000
 */

import { ProductType } from './models/types/ProductType';
import { UserType } from './models/types/UserType';
import { datetime } from '../../references/OpraBuiltInTypes/simple-types';

/**
 * Purchase details
 *
 * @url http:/localhost:3000/$schema/#types/PurchaseType
 */
export interface PurchaseType {
  /**
   * 
   */
  id?: string;

  /**
   * 
   */
  userId?: string;

  /**
   * 
   */
  productId?: string;

  /**
   * 
   */
  quantity?: number;

  /**
   * 
   */
  purchasedAt?: datetime;

  /**
   * 
   */
  user?: UserType;

  /**
   * 
   */
  product?: ProductType;
}

