/* #!oprimp_auto_generated!# !! Do NOT remove this line */
/* eslint-disable */
// noinspection SpellCheckingInspection

/* Generated by OPRA Code Generator, Version 1.21.0 */
/*
 * Opra built-in types
 * Id: 2124f2381d34a63b3c6f595ff0792897
 * Version: 1.0
 * http://localhost:3001
 */

/**
 * An integer number
 *
 * @url https:/oprajs.com/spec/v1.0/$schema/#types/integer
 */
export type integer = number;

/**
 * A stream of bytes, base64 encoded
 *
 * @url https:/oprajs.com/spec/v1.0/$schema/#types/base64
 */
export type base64 = string;

/**
 * A full datetime value
 *
 * @url https:/oprajs.com/spec/v1.0/$schema/#types/datetime
 */
export type datetime = string;

/**
 * A full datetime value with time zone information
 *
 * @url https:/oprajs.com/spec/v1.0/$schema/#types/datetimetz
 */
export type datetimetz = string;

/**
 * A date without time
 *
 * @url https:/oprajs.com/spec/v1.0/$schema/#types/date
 */
export type date = string;

/**
 * An email value
 *
 * @url https:/oprajs.com/spec/v1.0/$schema/#types/email
 */
export type email = string;

/**
 * Field path
 *
 * @url https:/oprajs.com/spec/v1.0/$schema/#types/fieldpath
 */
export type fieldpath = string;

/**
 * A query filter
 *
 * @url https:/oprajs.com/spec/v1.0/$schema/#types/filter
 */
export type filter = object;

/**
 * A MongoDB ObjectID value
 *
 * @url https:/oprajs.com/spec/v1.0/$schema/#types/ObjectId
 */
export type ObjectId = object;

/**
 * Specifies a point in time using a 24-hour clock notation. Format: 
* YYYY-[MM-[DD-[T?HH:[MM:[SS[.S[S[S[S]]]]]]]]][+/-ZZ:ZZ].
 *
 * @url https:/oprajs.com/spec/v1.0/$schema/#types/partialdate
 */
export type partialdate = string;

/**
 * Time string in 24h format
 *
 * @url https:/oprajs.com/spec/v1.0/$schema/#types/time
 */
export type time = string;

/**
 * A Uniform Resource Identifier Reference (RFC 3986 icon) value
 *
 * @url https:/oprajs.com/spec/v1.0/$schema/#types/url
 */
export type url = string;

/**
 * A Universal Unique Identifier (UUID) value
 *
 * @url https:/oprajs.com/spec/v1.0/$schema/#types/uuid
 */
export type uuid = string;

