/* #!oprimp_auto_generated!# !! Do NOT remove this line */
/* eslint-disable */
// noinspection SpellCheckingInspection

/* Generated by OPRA Code Generator, Version 1.21.0 */
/*
 * undefined
 * Id: 26385b66f3cc91470d992c4b20ab256e
 * Version: undefined
 * http://localhost:3000
 */

import { datetime } from '../../references/OpraBuiltInTypes/simple-types';

/**
 * User details
 *
 * @url http:/localhost:3000/$schema/#types/UserType
 */
export interface UserType {
  /**
   * 
   */
  id?: string;

  /**
   * 
   */
  email?: string;

  /**
   * 
   */
  firstName?: string;

  /**
   * 
   */
  lastName?: string;

  /**
   * 
   */
  isActive?: boolean;

  /**
   * 
   */
  createdAt?: datetime;
}

