/* #!oprimp_auto_generated!# !! Do NOT remove this line */
/* eslint-disable */
// noinspection SpellCheckingInspection

/* Generated by OPRA Code Generator, Version 1.21.0 */
/*
 * Opra built-in types
 * Id: 2124f2381d34a63b3c6f595ff0792897
 * Version: 1.0
 * http://localhost:3001
 */

/**
 * Operation result
 *
 * @url https:/oprajs.com/spec/v1.0/$schema/#types/OperationResult
 */
export interface OperationResult {
  /**
   * 
   */
  affected?: number;

  /**
   * 
   */
  totalMatches?: number;

  /**
   * 
   */
  context?: string;

  /**
   * 
   */
  type?: string;

  /**
   * 
   */
  message?: string;

  /**
   * 
   */
  payload?: any;

  /**
   * 
   */
  errors?: object[];
}

