/* #!oprimp_auto_generated!# !! Do NOT remove this line */
/* eslint-disable */
// noinspection SpellCheckingInspection

/* Generated by OPRA Code Generator, Version 1.21.0 */
/*
 * undefined
 * Id: e3023b67a2e3307059640dfdb5f80f1a
 * Version: undefined
 * http://localhost:3001
 */

import { OperationResult } from '@opra/common';
import { HttpRequestObservable, kClient, OpraHttpClient } from '@opra/client';
import { PartialDTO } from 'ts-gems';
import { HttpControllerNode } from '../http-controller-node';
import { ShipmentType } from '../models/types/ShipmentType';

/** 
 * Shipment API endpoints
 * @class ShipmentController
 * @apiUrl http:/localhost:3001/shipments
 */
export class ShipmentController extends HttpControllerNode {

  /**
   * @param {OpraHttpClient} client - OpraHttpClient instance to operate
   * @constructor
   */  
  constructor(client: OpraHttpClient) {
    super(client);
  }

  /** 
   * findMany operation
   * @param {object} $params - Available parameters for the operation
   * @param {object} [$params.limit]  - Determines number of returning instances
   * @param {object} [$params.skip]  - Determines number of returning instances
   * @param {boolean} [$params.count]  - Counts all matching instances if enabled
   * @param {object[]} [$params.projection]  - Determines fields projection
   * @apiUrl http:/localhost:3001/shipments    
   */
  findMany(
    $params?: {
      limit?: number;
      skip?: number;
      count?: boolean;
      projection?: string[];
      filter?: string | any;
    }
  ): HttpRequestObservable<OperationResult<PartialDTO<ShipmentType>[]>>{
    const url = this._prepareUrl('/shipments', {});
    return this[kClient].request(url, { method: 'GET', params: $params as any});
  };

  /** 
   * get operation
   * @param {object} $params - Available parameters for the operation
   * @param {object[]} [$params.projection]  - Determines fields projection
   * @apiUrl http:/localhost:3001/shipments    
   */
  get(
    $params?: {
      projection?: string[];
    }
  ): HttpRequestObservable<OperationResult<PartialDTO<ShipmentType>> | undefined>{
    const url = this._prepareUrl('/shipments', {});
    return this[kClient].request(url, { method: 'GET', params: $params as any});
  };
}