/* #!oprimp_auto_generated!# !! Do NOT remove this line */
/* eslint-disable */
// noinspection SpellCheckingInspection

/* Generated by OPRA Code Generator, Version 1.21.0 */
/*
 * undefined
 * Id: 058f9f43c1e667cf3ad9c1a0dff3cc62
 * Version: undefined
 * http://localhost:3000
 */

import { kClient, OpraHttpClient } from '@opra/client';

const PARAM_PATTERN = /:\w+/g;

export class HttpControllerNode {
  readonly [kClient]: OpraHttpClient;

  constructor(client: OpraHttpClient) {
    this[kClient] = client;
  }
  
  protected _prepareUrl(url: string, params: Record<string, any>): string {
    return url.replace(PARAM_PATTERN, s => {
      return params[s.substring(1)] || '';
    });
  }
}
