/* #!oprimp_auto_generated!# !! Do NOT remove this line */
/* eslint-disable */
// noinspection SpellCheckingInspection

/* Generated by OPRA Code Generator, Version 1.21.0 */
/*
 * undefined
 * Id: 416c049ef2d4b419053eb62787a4293c
 * Version: undefined
 * http://localhost:3000
 */

import { kClient, OpraHttpClient } from '@opra/client';
import { AuthController } from './api/AuthController';
import { ProductController } from './api/ProductController';
import { PurchaseController } from './api/PurchaseController';
import { UserController } from './api/UserController';

/** 
 * Test API
 * @class OpraTest
 * @url http:/localhost:3000/$schema
 */
export class OpraTest {
  readonly [kClient]: OpraHttpClient;
  readonly $product: ProductController;
  readonly $user: UserController;
  readonly $purchase: PurchaseController;
  readonly $auth: AuthController;

  constructor(client: OpraHttpClient) {
    this[kClient] = client;
    this.$product = new ProductController(client);
    this.$user = new UserController(client);
    this.$purchase = new PurchaseController(client);
    this.$auth = new AuthController(client);
  }
}