/* #!oprimp_auto_generated!# !! Do NOT remove this line */
/* eslint-disable */
// noinspection SpellCheckingInspection

/* Generated by OPRA Code Generator, Version 1.21.0 */
/*
 * undefined
 * Id: 416c049ef2d4b419053eb62787a4293c
 * Version: undefined
 * http://localhost:3000
 */

import { HttpRequestObservable, kClient, OpraHttpClient } from '@opra/client';
import { DTO } from 'ts-gems';
import { HttpControllerNode } from '../http-controller-node';
import { LoginInputType } from '../models/types/LoginInputType';
import { LoginResponseType } from '../models/types/LoginResponseType';

/** 
 * Authentication endpoints
 * @class AuthController
 * @apiUrl http:/localhost:3000/auth
 */
export class AuthController extends HttpControllerNode {

  /**
   * @param {OpraHttpClient} client - OpraHttpClient instance to operate
   * @constructor
   */  
  constructor(client: OpraHttpClient) {
    super(client);
  }

  /** 
   * Authenticate a user and return a JWT
   * @param {LoginInputType} $body  - Login payload
   * @apiUrl http:/localhost:3000/auth/login    
   */
  login($body: DTO<LoginInputType>
  ): HttpRequestObservable<DTO<LoginResponseType>>{
    const url = this._prepareUrl('/auth/login', {});
    return this[kClient].request(url, { method: 'POST', body: $body});
  };
}