/* #!oprimp_auto_generated!# !! Do NOT remove this line */
/* eslint-disable */
// noinspection SpellCheckingInspection

/* Generated by OPRA Code Generator, Version 1.21.0 */
/*
 * undefined
 * Id: 058f9f43c1e667cf3ad9c1a0dff3cc62
 * Version: undefined
 * http://localhost:3000
 */

import { OperationResult } from '@opra/common';
import { HttpRequestObservable, kClient, OpraHttpClient } from '@opra/client';
import { PartialDTO, DTO } from 'ts-gems';
import { HttpControllerNode } from '../http-controller-node';
import { UserType } from '../models/types/UserType';

/** 
 * Users collection
 * @class UserController
 * @apiUrl http:/localhost:3000/users
 */
export class UserController extends HttpControllerNode {

  /**
   * @param {OpraHttpClient} client - OpraHttpClient instance to operate
   * @constructor
   */  
  constructor(client: OpraHttpClient) {
    super(client);
  }

  /** 
   * findMany operation
   * @param {object} $params - Available parameters for the operation
   * @param {object} [$params.limit]  - Determines number of returning instances
   * @param {object} [$params.skip]  - Determines number of returning instances
   * @param {boolean} [$params.count]  - Counts all matching instances if enabled
   * @param {object[]} [$params.projection]  - Determines fields projection
   * @apiUrl http:/localhost:3000/users    
   */
  findMany(
    $params?: {
      limit?: number;
      skip?: number;
      count?: boolean;
      projection?: string[];
    }
  ): HttpRequestObservable<OperationResult<PartialDTO<UserType>[]>>{
    const url = this._prepareUrl('/users', {});
    return this[kClient].request(url, { method: 'GET', params: $params as any});
  };

  /** 
   * get operation
   * @param {object} $params - Available parameters for the operation
   * @param {object[]} [$params.projection]  - Determines fields projection
   * @apiUrl http:/localhost:3000/users    
   */
  get(
    $params?: {
      projection?: string[];
    }
  ): HttpRequestObservable<OperationResult<PartialDTO<UserType>> | undefined>{
    const url = this._prepareUrl('/users', {});
    return this[kClient].request(url, { method: 'GET', params: $params as any});
  };

  /** 
   * create operation
   * @param {UserType} $body  - User details
   * @param {object} $params - Available parameters for the operation
   * @param {object[]} [$params.projection]  - Determines fields projection
   * @apiUrl http:/localhost:3000/users    
   */
  create($body: DTO<UserType>, 
    $params?: {
      projection?: string[];
    }
  ): HttpRequestObservable<OperationResult<PartialDTO<UserType>>>{
    const url = this._prepareUrl('/users', {});
    return this[kClient].request(url, { method: 'POST', body: $body, params: $params as any});
  };

  /** 
   * update operation
   * @param {UserType} $body  - User details
   * @param {object} $params - Available parameters for the operation
   * @param {object[]} [$params.projection]  - Determines fields projection
   * @apiUrl http:/localhost:3000/users    
   */
  update($body: PartialDTO<UserType>, 
    $params?: {
      projection?: string[];
    }
  ): HttpRequestObservable<OperationResult<PartialDTO<UserType>> | undefined>{
    const url = this._prepareUrl('/users', {});
    return this[kClient].request(url, { method: 'PATCH', body: $body, params: $params as any});
  };

  /** 
   * delete operation
   * @apiUrl http:/localhost:3000/users    
   */
  delete(
  ): HttpRequestObservable<OperationResult>{
    const url = this._prepareUrl('/users', {});
    return this[kClient].request(url, { method: 'DELETE'});
  };
}